from fpdf import FPDF
import io

def generate_pdf(name, sport, grade, gpa, plan, score):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(200, 10, f"{name}'s Recruiting Report", ln=True, align='C')

    pdf.set_font("Arial", "", 12)
    pdf.ln(10)
    pdf.cell(200, 10, f"Sport: {sport}", ln=True)
    pdf.cell(200, 10, f"Grade: {grade}", ln=True)
    pdf.cell(200, 10, f"GPA: {gpa}", ln=True)
    pdf.cell(200, 10, f"Recommended Plan: {plan}", ln=True)
    pdf.cell(200, 10, f"Match Strength Score: {score}", ln=True)

    pdf.ln(10)
    pdf.multi_cell(0, 10, "This report was generated by ScoutBot using your inputs. Use this as your guide to take the next step in your athletic journey.")

    buffer = io.BytesIO()
    pdf.output(buffer)
    return buffer.getvalue()
